### ISSUE TITLE
Some tips

### ISSUE THREAD

**Issue by jahodovykolac** [Ian35682/Resourceplus#1]
Please don't make your mod dependent on Civ5Expansionmod, Unciv has already implemented Hills as terrain features.
Otherwise great mod! 👍

**Comment by Ian35682** [comment]
Thank you for your feedback
Current version have updated and removed Desert Hill
If you got any advice feel free to email me or dm me on discord

jahodovykolac ***@***.***> 於 2021年6月17日 週四 上午2:14 寫道：

**Comment by jahodovykolac** [comment]
Thanks! Your mod is one of the best mods for Unciv. I would just have a tip if it wouldn't annoy you. Potato can spawn on Tundra, but Farm can be built on Tundra if it is next to fresh water, so Potato shouldn't spawn there.
Otherwise, awesome mod!
